---
- name: Setup database
  hosts: database
  become: yes
  vars_files:
   - /vagrant/variables.yaml
  
  tasks:
    - name: Update & Upgrade the System
      apt:
        update_cache: yes
        upgrade: yes 
    
    - name: Install MYSQL packages
      apt:
        name:
            - mysql-server
            - python3
            - firewalld
  
    - name: Open port 3306
      ansible.posix.firewalld:
        port: 3306/tcp
        permanent: yes
        state: enabled
    
    - name: Create Wordpress Database   
      shell: 'mysql < wpDB.sql'
      args:
        chdir: /vagrant/
    
    - name: Configure mysqld.cnf file to allow connections on ip 0.0.0.0 (external connections)
      shell: 'sed -i "0,/127.0.0.1/ s/127.0.0.1/0.0.0.0/" /etc/mysql/mysql.conf.d/mysqld.cnf'
      
    - name: Restart MySQL  
      service:
        name: mysql
        state: restarted